#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $MAFIA_REPO == "mafiabot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0gxTTRONUhVMFAvTUFGSUEtVVNFUkJPVC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $MAFIA_REPO == "MAFIABOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0gxTTRONUhVMFAvTUFGSUEtVVNFUkJPVC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $MAFIA_REPO =~ $regex ]]
    then
        if [[ $MAFIA_REPO_BRANCH ]]
        then
            echo "${MAFIA_REPO}/archive/${MAFIA_REPO_BRANCH}.zip"
        else
            echo "${MAFIA_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL0gxTTRONUhVMFAvTUFGSUEtVVNFUkJPVC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="mafiabot.zip"
    echo "  𝘿𝙊𝙒𝙉𝙇𝙊𝘼𝘿𝙄𝙉𝙂 𝙎𝙊𝙐𝙍𝘾𝙀 𝘾𝙊𝘿𝙀 ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    MAFIAPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "𝘿𝙊𝙉𝙀"
    echo "  𝘾𝙇𝙀𝘼𝙉𝙄𝙉𝙂 ..."
    rm -rf "$zippath"
    sleep 5
    cd $MAFIAPATH
    echo "    𝙎𝙏𝘼𝙍𝙏𝙄𝙉𝙂 𝙉𝙊𝙄𝙉𝙊𝙄 𝘽𝙊𝙏 📻  "
    echo "
                          𝙉 𝙊 𝙄 𝙉 𝙊 𝙄 🌸
   

    python3 ./setup/updater.py ./requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
